version: '3'
services:
  monitoring:
    build: .
    environment:
      - SMTP_HOST=your_aws_smtp_host
      - SMTP_PORT=587
      - SMTP_USERNAME=your_aws_smtp_username
      - SMTP_PASSWORD=your_aws_smtp_password
      - FROM_EMAIL=sender@example.com
      - TO_EMAIL=recipient@example.com
      - HOSTS_URL=https://example.com/hosts.csv